# Generated by Django 4.0.4 on 2022-05-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='last_edition',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01 11:11'),
            preserve_default=False,
        ),
    ]
